[
	{
		"OHOS_ABILITY_CAMERA_POSITION":"OHOS_CAMERA_POSITION_BACK",
		"OHOS_ABILITY_CAMERA_FOLD_STATUS":"OHOS_CAMERA_FOLD_STATUS_EXPANDED_FOLDED",
		"OHOS_SENSOR_ORIENTATION":"90"
	},
	{
		"OHOS_ABILITY_CAMERA_POSITION":"OHOS_CAMERA_POSITION_FRONT",
		"OHOS_ABILITY_CAMERA_FOLDSCREEN_TYPE":"OHOS_CAMERA_FOLDSCREEN_INNER",
		"OHOS_ABILITY_CAMERA_FOLD_STATUS":"OHOS_CAMERA_FOLD_STATUS_EXPANDED",
		"OHOS_SENSOR_ORIENTATION":"270"
	},
	{
		"OHOS_ABILITY_CAMERA_POSITION":"OHOS_CAMERA_POSITION_FRONT",
		"OHOS_ABILITY_CAMERA_FOLDSCREEN_TYPE":"OHOS_CAMERA_FOLDSCREEN_OUTER",
		"OHOS_ABILITY_CAMERA_FOLD_STATUS":"OHOS_CAMERA_FOLD_STATUS_FOLDED",
		"OHOS_SENSOR_ORIENTATION":"270"
	}
]