[
	{
		"OHOS_ABILITY_CAMERA_POSITION":"OHOS_CAMERA_POSITION_BACK",
		"OHOS_SENSOR_ORIENTATION":"90"
	},
	{
		"OHOS_ABILITY_CAMERA_POSITION":"OHOS_CAMERA_POSITION_FRONT",
		"OHOS_SENSOR_ORIENTATION":"270"
	}
]